---
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  become: true
  apt:
    autoremove: yes

- name: "install NodeJS and NPM"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install PM2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "create a directory"
  file:
    path: ~/backend-app
    state: directory

- name: "copy backend artifact"
  become: true
  unarchive:
    src: project/artifact.tar.gz
    dest: ~/backend-app

# - name: "Extract the zipped artifact"
#   become: true
#   shell: |
#     tar -xvzf artifact.tar.gz -C ~/backend-app
#     echo "**** ls in backend-app DIR ****"
#     ls -l ~/backend-app

- name: "Execute node"
  shell: |
    cd backend-app
    npm install
    pm2 stop default
    pm2 start npm -- start